### ISSUE TITLE
Bokeh blur needed

### ISSUE THREAD

**Issue by simonmysun** [jonkpirateboy/refocus#1]
I don't think this looks like any effects from camera. It's Gauss blur rather than bokeh blur. 

It's easy to distinguish: https://en.wikipedia.org/wiki/File:Faux-bokeh-comparison.jpg

**Comment by tomten** [comment]
Bokeh? Är du tokeh? It's the focusing/unfocusing that resembles a camera, not the actual blur. 

I couldn't find a browser implementation of bokeh; can you?

**Comment by jonkpirateboy** [comment]
@simonmysun, what @tomten said.
